### ISSUE TITLE
Cannot read property 'magnetLink' of undefined

### ISSUE THREAD

**Issue by TheTinyBit** [kshvmdn/show-me-a-movie#2]
I wanted to stream the movie _Fired Up!_ and it gave me the following output before exiting:

```
show-me-a-movie tt1083456
> Requesting torrent data for Fired Up!...
> Torrent data received, loading stream...
Cannot read property 'magnetLink' of undefined
```

**Comment by kashav** [comment]
Thanks for letting me know; i'll look into it! 

My preliminary thoughts are that the search returns nothing, meaning there's no torrent available for the movie. Only solution might be to add better error handling.

**Comment by kashav** [comment]
Looks like that _was_ the case. Fixed (temporarily, at least) in https://github.com/kshvmdn/show-me-a-movie/commit/6456e7edfb51bb11fe03a5bde25bc00bf6dab061.

Closing for now, might look into using a different package for movies that have no tpb torrents. Thanks for the issue!
